# @type {import("prettier").Config}
useTabs: true
trailingComma: all
singleQuote: true
printWidth: 100
tabWidth: 2
arrowParens: always
plugins:
  - prettier-plugin-astro
overrides:
  - files: "*.astro"
    options:
      parser: astro
      tabWidth: 2
      singleQuote: true
